Repository Real-Man-Club/Baekjoon, pull requests merged in 2022-05, with the labels that each got.

#45 18회차
  Mootata/17회차/2841.외계인의 기타 연주.py
  Mootata/18주차/1059.좋은 구간.py
  Mootata/18주차/1080.행렬.py
  Mootata/18주차/10871.X보다 작은 수.py
  Mootata/18주차/1339.단어 수학.py
  Mootata/18주차/14720.우유 축제.py
  Mootata/18주차/14916.거스름돈.py
  Mootata/18주차/2750.수 정렬하기.py
Labels: Langueages/Python

#46 18회차
  devappmin/1080.행렬.py
  devappmin/10816.숫자 카드 2.py
  devappmin/1339.단어 수학.py
  devappmin/15726.이칙연산.py
  devappmin/24900.한별 찍기.txt
  devappmin/25083.새싹.py
Labels: Langueages/Python

#48 19회차
  devappmin/1013.Contact.py
  devappmin/1049.기타줄.py
  devappmin/11497.통나무 건너뛰기.py
  devappmin/14405.피카츄.py
  devappmin/15652.N과 M(4).py
  devappmin/15654.N과 M(5).py
  devappmin/15657.N과 M(8).py
  devappmin/15663.N과 M(9).py
  devappmin/15666.N과 M(12).py
  devappmin/17609.회문.py
  devappmin/18405.경쟁적 전염.py
  devappmin/2671.잠수함식별.py
  devappmin/9996.한국이 그리울 땐 서버에 접속하지.py
Labels: Langueages/Python

#47 19회차
  Mootata/19주차/1013.contact.py
  Mootata/19주차/1032.명령 프롬프트.py
  Mootata/19주차/1110.더하기 사이클.py
  Mootata/19주차/1145.적어도 대부분의 배수.py
  Mootata/19주차/1152.단어의 개수.py
  Mootata/19주차/17609.회문.py
  Mootata/19주차/18405.경쟁적 전염.py
Labels: Langueages/Python

#50 20회차
  devappmin/10830.행렬 제곱.py
  devappmin/11725.트리의 부모 찾기.py
  devappmin/15904.UCPC는 무엇의 약자일까.py
  devappmin/2439.별 찍기 - 2.py
  devappmin/2448.별 찍기 - 11.py
  devappmin/5337.웰컴.txt
  devappmin/5338.마이크로소프트 로고.txt
  devappmin/6603.로또.py
Labels: Langueages/Python

#49 20회차
  Mootata/20회자/10830.행렬 제곱.py
  Mootata/20회자/1157.단어 공부.py
  Mootata/20회자/1159.농구 경기.py
  Mootata/20회자/11725.트리의 부모 찾기.py
  Mootata/20회자/1173.운동.py
  Mootata/20회자/1212.8진수 2진수.py
  Mootata/20회자/1225.이상한 곱셈.py
  Mootata/20회자/2448.별 찍기 - 11.py
Labels: Langueages/Python

#52 21회차
  Mootata/21회차/11660.구간 합 구하기 5.py
  Mootata/21회차/1252.이진수 덧셈.py
  Mootata/21회차/1350.진짜 공간.py
  Mootata/21회차/1449.수리공 항승.py
  Mootata/21회차/17070.파이프 옮기기 1.py
  Mootata/README.md
Labels: Languages/Python

#51 21회차
  devappmin/11660.구간 합 구하기 5.py
  devappmin/1449.수리공 항승.py
  devappmin/15596.정수 N개의 합.py
  devappmin/17069.파이프 옮기기 2.py
  devappmin/17070.파이프 옮기기 1.py
  devappmin/2502.떡 먹는 호랑이.py
  devappmin/2845.파티가 끝나고 난 뒤.py
  devappmin/9653.스타워즈 로고.txt
  devappmin/9654.나부 함대 데이터.txt
Labels: Languages/Python, Languages/Text

#53 22회차
  Mootata/22회차/13549.숨바꼭질 3.py
  Mootata/22회차/1547.공.py
  Mootata/22회차/17144.미세먼지 안녕!.py
  Mootata/22회차/18428.감시 피하기.py
Labels: Languages/Python

#54 22회차
  devappmin/11382.꼬마 정민.py
  devappmin/12852.1로 만들기 2.py
  devappmin/13549.숨바꼭질 3.py
  devappmin/1550.16진수.py
  devappmin/15649.N과 M(1).py
  devappmin/15651.N과 M (3).py
  devappmin/15733.나는 누구인가.txt
  devappmin/17144.미세먼지 안녕!.py
  devappmin/18428.감시 피하기.py
Labels: Languages/Python, Languages/Text
